// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRidplZ4Tw7gKrNMdABb9rXHLDbuj9STc',
    appId: '1:432990202758:web:ac994f639606f578525a07',
    messagingSenderId: '432990202758',
    projectId: 'my-travel-stories-by-ai',
    authDomain: 'my-travel-stories-by-ai.firebaseapp.com',
    storageBucket: 'my-travel-stories-by-ai.appspot.com',
    measurementId: 'G-5QJGH7LRD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQZL0qpvnFunBbSwCLKzfq9RRB4TppAU',
    appId: '1:432990202758:android:6e0cdedd93cd0e14525a07',
    messagingSenderId: '432990202758',
    projectId: 'my-travel-stories-by-ai',
    storageBucket: 'my-travel-stories-by-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWgXu1pLsOhxzPfhZuEjIDwttIINU0hyU',
    appId: '1:432990202758:ios:8305d351d0b2ae93525a07',
    messagingSenderId: '432990202758',
    projectId: 'my-travel-stories-by-ai',
    storageBucket: 'my-travel-stories-by-ai.appspot.com',
    iosBundleId: 'com.example.myTravelStories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWgXu1pLsOhxzPfhZuEjIDwttIINU0hyU',
    appId: '1:432990202758:ios:76ebcd3768f1e5c7525a07',
    messagingSenderId: '432990202758',
    projectId: 'my-travel-stories-by-ai',
    storageBucket: 'my-travel-stories-by-ai.appspot.com',
    iosBundleId: 'com.example.myTravelStories.RunnerTests',
  );
}
